/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemadeobjetosperdidos;

/**
 *
 * @author ASUS
 */
public class Busqueda1 extends javax.swing.JFrame {

    /**
     * Creates new form busqueda
     */
    public Busqueda1() {
        
        setUndecorated(true);
        initComponents();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        busquedaPorCodigoPanelTitulo = new javax.swing.JPanel();
        busquedaPorCodigoPanel = new javax.swing.JPanel();
        IDTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrarInformacionTextArea = new javax.swing.JTextArea();
        salirButton = new javax.swing.JButton();
        buscarButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setBackground(new java.awt.Color(0, 0, 0));
        Menu.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        Menu.setPreferredSize(new java.awt.Dimension(500, 700));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        busquedaPorCodigoPanelTitulo.setBackground(new java.awt.Color(0, 0, 0));
        busquedaPorCodigoPanelTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), " BUSQUEDA POR CODIGO ID ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        busquedaPorCodigoPanel.setBackground(new java.awt.Color(0, 0, 0));
        busquedaPorCodigoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), " INGRESE EL ID DEL OBJETO A BUSCAR:    ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        busquedaPorCodigoPanel.setForeground(new java.awt.Color(255, 255, 255));

        IDTextField.setBackground(new java.awt.Color(0, 0, 0));
        IDTextField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        IDTextField.setForeground(new java.awt.Color(255, 255, 255));
        IDTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IDTextField.setText(" Ejm: 1, 2, 3,... ");
        IDTextField.setToolTipText("");
        IDTextField.setBorder(null);
        IDTextField.setCaretColor(new java.awt.Color(102, 102, 102));
        IDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout busquedaPorCodigoPanelLayout = new javax.swing.GroupLayout(busquedaPorCodigoPanel);
        busquedaPorCodigoPanel.setLayout(busquedaPorCodigoPanelLayout);
        busquedaPorCodigoPanelLayout.setHorizontalGroup(
            busquedaPorCodigoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busquedaPorCodigoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
        );
        busquedaPorCodigoPanelLayout.setVerticalGroup(
            busquedaPorCodigoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, busquedaPorCodigoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setBorder(null);

        mostrarInformacionTextArea.setBackground(new java.awt.Color(0, 0, 0));
        mostrarInformacionTextArea.setColumns(20);
        mostrarInformacionTextArea.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        mostrarInformacionTextArea.setForeground(new java.awt.Color(255, 255, 255));
        mostrarInformacionTextArea.setRows(5);
        mostrarInformacionTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), " INFORMACION: ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        mostrarInformacionTextArea.setFocusable(false);
        jScrollPane1.setViewportView(mostrarInformacionTextArea);

        salirButton.setBackground(new java.awt.Color(0, 0, 0));
        salirButton.setForeground(new java.awt.Color(255, 255, 255));
        salirButton.setText("Salir");
        salirButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        salirButton.setFocusPainted(false);
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        buscarButton1.setBackground(new java.awt.Color(0, 0, 0));
        buscarButton1.setForeground(new java.awt.Color(255, 255, 255));
        buscarButton1.setText("Buscar");
        buscarButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        buscarButton1.setFocusPainted(false);
        buscarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout busquedaPorCodigoPanelTituloLayout = new javax.swing.GroupLayout(busquedaPorCodigoPanelTitulo);
        busquedaPorCodigoPanelTitulo.setLayout(busquedaPorCodigoPanelTituloLayout);
        busquedaPorCodigoPanelTituloLayout.setHorizontalGroup(
            busquedaPorCodigoPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busquedaPorCodigoPanelTituloLayout.createSequentialGroup()
                .addGroup(busquedaPorCodigoPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(busquedaPorCodigoPanelTituloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(busquedaPorCodigoPanelTituloLayout.createSequentialGroup()
                        .addGroup(busquedaPorCodigoPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(busquedaPorCodigoPanelTituloLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(busquedaPorCodigoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(busquedaPorCodigoPanelTituloLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(buscarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(busquedaPorCodigoPanelTituloLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addContainerGap())
        );
        busquedaPorCodigoPanelTituloLayout.setVerticalGroup(
            busquedaPorCodigoPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busquedaPorCodigoPanelTituloLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(busquedaPorCodigoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        Menu.add(busquedaPorCodigoPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 440, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_salirButtonActionPerformed

    private void buscarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButton1ActionPerformed
        
        String[] objeto = Objeto.getLista().get(Integer.parseInt(IDTextField.getText())-1);
        
        mostrarInformacionTextArea.setText("");
        
        mostrarInformacionTextArea.append("\n");
        mostrarInformacionTextArea.append(" ------- INFORMACION DEL OBJETO ---------------------\n ");
        mostrarInformacionTextArea.append("\n");
        mostrarInformacionTextArea.append(" - NOMBRE DEL OBJETO: "+ objeto[0]+"\n");
        mostrarInformacionTextArea.append(" - DESCRIPCION: "+ objeto[1]+"\n");
        mostrarInformacionTextArea.append(" - CATEGORIA: "+ objeto[2]+"\n");
        mostrarInformacionTextArea.append(" - LUGAR Y FEHCA: "+ objeto[3]+"\n");
        mostrarInformacionTextArea.append(" - REPORTANTE: "+ objeto[4]+"\n");
        mostrarInformacionTextArea.append(" - ESTADO DEL OBJETO: "+ objeto[5]+"\n");
        mostrarInformacionTextArea.append("\n");
        
        mostrarInformacionTextArea.append("  ------- INFORMACION DEL RECLAMANTE ---------------------\n ");
        mostrarInformacionTextArea.append("\n");
        mostrarInformacionTextArea.append(" - NOMBRE DEL RECLAMANTE: "+ objeto[6]+"\n");
        mostrarInformacionTextArea.append(" - CODIGO DEL RECLAMANTE: "+ objeto[7]+"\n");
        mostrarInformacionTextArea.append(" - CORREO DEL RECLAMANTE: "+ objeto[8]+"\n");
        mostrarInformacionTextArea.append(" - TELEFONO DEL RECLAMANTE: "+ objeto[9]+"\n");  
        mostrarInformacionTextArea.append("\n");

        // TODO add your handling code here:
    }//GEN-LAST:event_buscarButton1ActionPerformed

    private void IDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDTextField;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton buscarButton1;
    private javax.swing.JPanel busquedaPorCodigoPanel;
    private javax.swing.JPanel busquedaPorCodigoPanelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mostrarInformacionTextArea;
    private javax.swing.JButton salirButton;
    // End of variables declaration//GEN-END:variables
}
