/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemadeobjetosperdidos;

/**
 *
 * @author ASUS
 */
public class busqueda extends javax.swing.JFrame {

    /**
     * Creates new form busqueda
     */
    public busqueda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        busquedaPorCodigoPanelTitulo = new javax.swing.JPanel();
        BuscarPorCodigoLabel = new javax.swing.JLabel();
        busquedaPorCodigoPanel = new javax.swing.JPanel();
        IDLabel = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        buscarButton1 = new javax.swing.JButton();
        mostrarInformacionTextField = new javax.swing.JTextField();
        busquedaPorCodigoPanelOpciones = new javax.swing.JPanel();
        salirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setBackground(new java.awt.Color(204, 204, 204));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BuscarPorCodigoLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        BuscarPorCodigoLabel.setForeground(new java.awt.Color(255, 255, 255));
        BuscarPorCodigoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BuscarPorCodigoLabel.setText("BUSQUEDA POR CODIGO ID");
        BuscarPorCodigoLabel.setToolTipText("");
        BuscarPorCodigoLabel.setAutoscrolls(true);

        javax.swing.GroupLayout busquedaPorCodigoPanelTituloLayout = new javax.swing.GroupLayout(busquedaPorCodigoPanelTitulo);
        busquedaPorCodigoPanelTitulo.setLayout(busquedaPorCodigoPanelTituloLayout);
        busquedaPorCodigoPanelTituloLayout.setHorizontalGroup(
            busquedaPorCodigoPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(busquedaPorCodigoPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(busquedaPorCodigoPanelTituloLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BuscarPorCodigoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        busquedaPorCodigoPanelTituloLayout.setVerticalGroup(
            busquedaPorCodigoPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(busquedaPorCodigoPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(busquedaPorCodigoPanelTituloLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BuscarPorCodigoLabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Menu.add(busquedaPorCodigoPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 120));

        busquedaPorCodigoPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        IDLabel.setText("INGRESE EL ID DEL OBJETO A BUSCAR:");

        IDTextField.setForeground(new java.awt.Color(102, 102, 102));
        IDTextField.setText("Ejm: 1, 2, 3,...");
        IDTextField.setToolTipText("");
        IDTextField.setCaretColor(new java.awt.Color(102, 102, 102));

        buscarButton1.setText("Buscar");
        buscarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButton1ActionPerformed(evt);
            }
        });

        mostrarInformacionTextField.setForeground(new java.awt.Color(102, 102, 102));
        mostrarInformacionTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mostrarInformacionTextField.setActionCommand("<Not Set>");
        mostrarInformacionTextField.setCaretColor(new java.awt.Color(102, 102, 102));
        mostrarInformacionTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        mostrarInformacionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarInformacionTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout busquedaPorCodigoPanelLayout = new javax.swing.GroupLayout(busquedaPorCodigoPanel);
        busquedaPorCodigoPanel.setLayout(busquedaPorCodigoPanelLayout);
        busquedaPorCodigoPanelLayout.setHorizontalGroup(
            busquedaPorCodigoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busquedaPorCodigoPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(busquedaPorCodigoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(busquedaPorCodigoPanelLayout.createSequentialGroup()
                        .addGroup(busquedaPorCodigoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buscarButton1)
                            .addComponent(IDLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mostrarInformacionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        busquedaPorCodigoPanelLayout.setVerticalGroup(
            busquedaPorCodigoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busquedaPorCodigoPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(busquedaPorCodigoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDLabel)
                    .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mostrarInformacionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Menu.add(busquedaPorCodigoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 380, 400));

        busquedaPorCodigoPanelOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout busquedaPorCodigoPanelOpcionesLayout = new javax.swing.GroupLayout(busquedaPorCodigoPanelOpciones);
        busquedaPorCodigoPanelOpciones.setLayout(busquedaPorCodigoPanelOpcionesLayout);
        busquedaPorCodigoPanelOpcionesLayout.setHorizontalGroup(
            busquedaPorCodigoPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busquedaPorCodigoPanelOpcionesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(salirButton)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        busquedaPorCodigoPanelOpcionesLayout.setVerticalGroup(
            busquedaPorCodigoPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busquedaPorCodigoPanelOpcionesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(salirButton)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        Menu.add(busquedaPorCodigoPanelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 130, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirButtonActionPerformed

    private void buscarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarButton1ActionPerformed

    private void mostrarInformacionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarInformacionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarInformacionTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new busqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuscarPorCodigoLabel;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton buscarButton1;
    private javax.swing.JPanel busquedaPorCodigoPanel;
    private javax.swing.JPanel busquedaPorCodigoPanelOpciones;
    private javax.swing.JPanel busquedaPorCodigoPanelTitulo;
    private javax.swing.JTextField mostrarInformacionTextField;
    private javax.swing.JButton salirButton;
    // End of variables declaration//GEN-END:variables
}
