/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemadeobjetosperdidos;

/**
 *
 * @author ASUS
 */
public class CodigoJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CodigoJFrame
     */
    public CodigoJFrame() {
        
        setUndecorated(true);
        initComponents();
        
        codigoIDTextField.setText(Integer.toString(Objeto.getLista().size()+1));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        asignacionDeCodigoIDPanel = new javax.swing.JPanel();
        codigoIDTextField = new javax.swing.JTextField();
        aceptarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setBackground(new java.awt.Color(0, 0, 0));
        Menu.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        Menu.setPreferredSize(new java.awt.Dimension(500, 700));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        asignacionDeCodigoIDPanel.setBackground(new java.awt.Color(0, 0, 0));
        asignacionDeCodigoIDPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), " ID DEL OBJETO:  ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        asignacionDeCodigoIDPanel.setForeground(new java.awt.Color(255, 255, 255));

        codigoIDTextField.setEditable(false);
        codigoIDTextField.setBackground(new java.awt.Color(0, 0, 0));
        codigoIDTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        codigoIDTextField.setForeground(new java.awt.Color(255, 255, 255));
        codigoIDTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codigoIDTextField.setToolTipText("");
        codigoIDTextField.setBorder(null);
        codigoIDTextField.setCaretColor(new java.awt.Color(102, 102, 102));
        codigoIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoIDTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout asignacionDeCodigoIDPanelLayout = new javax.swing.GroupLayout(asignacionDeCodigoIDPanel);
        asignacionDeCodigoIDPanel.setLayout(asignacionDeCodigoIDPanelLayout);
        asignacionDeCodigoIDPanelLayout.setHorizontalGroup(
            asignacionDeCodigoIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asignacionDeCodigoIDPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(codigoIDTextField)
                .addContainerGap())
        );
        asignacionDeCodigoIDPanelLayout.setVerticalGroup(
            asignacionDeCodigoIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(codigoIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Menu.add(asignacionDeCodigoIDPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 320, 80));

        aceptarButton.setBackground(new java.awt.Color(0, 0, 0));
        aceptarButton.setForeground(new java.awt.Color(255, 255, 255));
        aceptarButton.setText("Aceptar");
        aceptarButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        aceptarButton.setFocusPainted(false);
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });
        Menu.add(aceptarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 260, 30));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("!El registro se completo correctamente¡");
        Menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void codigoIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoIDTextFieldActionPerformed


        // TODO add your handling code here:
    }//GEN-LAST:event_codigoIDTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JButton aceptarButton;
    private javax.swing.JPanel asignacionDeCodigoIDPanel;
    private javax.swing.JTextField codigoIDTextField;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
