/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemadeobjetosperdidos;

import java.util.Arrays;

/**
 *
 * @author ASUS
 */
public class ListarJFrame extends javax.swing.JFrame {

    /**
     * Creates new form Listar
     */
    public ListarJFrame() {
        
        setUndecorated(true);
        initComponents();
        
        for (int i = 0; i < Objeto.getLista().size(); i++) {

            String[] objeto = Objeto.getLista().get(i);
            objeto[1] = "NO DISPONIBLE";
            
            listadoTextArea.append("\n");
            listadoTextArea.append("\n");
            
            listadoTextArea.append(" REGISTRO ID ("+(i+1)+"):\n");
            
            for (int j = 0; j < 10; j++) {
                
                listadoTextArea.append("   - "+objeto[j]+"\n");

            }
            
            listadoTextArea.append("\n");
            listadoTextArea.append("-------------------------------");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        listarObjetoPanelTitulo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listadoTextArea = new javax.swing.JTextArea();
        salirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setBackground(new java.awt.Color(0, 0, 0));
        Menu.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        Menu.setForeground(new java.awt.Color(255, 255, 255));
        Menu.setPreferredSize(new java.awt.Dimension(500, 700));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listarObjetoPanelTitulo.setBackground(new java.awt.Color(0, 0, 0));
        listarObjetoPanelTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), " LISTA DE OBJETOS REGISTRADOS  ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jScrollPane1.setBorder(null);

        listadoTextArea.setBackground(new java.awt.Color(0, 0, 0));
        listadoTextArea.setColumns(20);
        listadoTextArea.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        listadoTextArea.setForeground(new java.awt.Color(255, 255, 255));
        listadoTextArea.setRows(5);
        listadoTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), " OBJETOS REGISTRADOS   ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jScrollPane1.setViewportView(listadoTextArea);

        salirButton.setBackground(new java.awt.Color(0, 0, 0));
        salirButton.setForeground(new java.awt.Color(255, 255, 255));
        salirButton.setText("Salir");
        salirButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        salirButton.setFocusPainted(false);
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listarObjetoPanelTituloLayout = new javax.swing.GroupLayout(listarObjetoPanelTitulo);
        listarObjetoPanelTitulo.setLayout(listarObjetoPanelTituloLayout);
        listarObjetoPanelTituloLayout.setHorizontalGroup(
            listarObjetoPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listarObjetoPanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(listarObjetoPanelTituloLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        listarObjetoPanelTituloLayout.setVerticalGroup(
            listarObjetoPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listarObjetoPanelTituloLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        Menu.add(listarObjetoPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 460, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_salirButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea listadoTextArea;
    private javax.swing.JPanel listarObjetoPanelTitulo;
    private javax.swing.JButton salirButton;
    // End of variables declaration//GEN-END:variables
}
