/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemadeobjetosperdidos;

/**
 *
 * @author ASUS
 */
public class Listar extends javax.swing.JFrame {

    /**
     * Creates new form Listar
     */
    public Listar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        listarObjetoPanelTitulo = new javax.swing.JPanel();
        registrarObjetoPerdidoLabel = new javax.swing.JLabel();
        listarObjetoPanel = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        nombreDelObjetoTextField = new javax.swing.JTextField();
        listarObjetoPanelOpciones = new javax.swing.JPanel();
        cancelarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setBackground(new java.awt.Color(204, 204, 204));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrarObjetoPerdidoLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        registrarObjetoPerdidoLabel.setForeground(new java.awt.Color(255, 255, 255));
        registrarObjetoPerdidoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrarObjetoPerdidoLabel.setText("LISTA DE OBJETOS REGISTRADOS}");
        registrarObjetoPerdidoLabel.setToolTipText("");
        registrarObjetoPerdidoLabel.setAutoscrolls(true);

        javax.swing.GroupLayout listarObjetoPanelTituloLayout = new javax.swing.GroupLayout(listarObjetoPanelTitulo);
        listarObjetoPanelTitulo.setLayout(listarObjetoPanelTituloLayout);
        listarObjetoPanelTituloLayout.setHorizontalGroup(
            listarObjetoPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listarObjetoPanelTituloLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(registrarObjetoPerdidoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        listarObjetoPanelTituloLayout.setVerticalGroup(
            listarObjetoPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listarObjetoPanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registrarObjetoPerdidoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        Menu.add(listarObjetoPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 120));

        listarObjetoPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nombreDelObjetoTextField.setForeground(new java.awt.Color(102, 102, 102));
        nombreDelObjetoTextField.setToolTipText("");
        nombreDelObjetoTextField.setCaretColor(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout listarObjetoPanelLayout = new javax.swing.GroupLayout(listarObjetoPanel);
        listarObjetoPanel.setLayout(listarObjetoPanelLayout);
        listarObjetoPanelLayout.setHorizontalGroup(
            listarObjetoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listarObjetoPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(nombreDelObjetoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        listarObjetoPanelLayout.setVerticalGroup(
            listarObjetoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listarObjetoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listarObjetoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombreDelObjetoTextField)
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        Menu.add(listarObjetoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 380, 400));

        listarObjetoPanelOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        cancelarButton.setText("Salir");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listarObjetoPanelOpcionesLayout = new javax.swing.GroupLayout(listarObjetoPanelOpciones);
        listarObjetoPanelOpciones.setLayout(listarObjetoPanelOpcionesLayout);
        listarObjetoPanelOpcionesLayout.setHorizontalGroup(
            listarObjetoPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listarObjetoPanelOpcionesLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(cancelarButton)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        listarObjetoPanelOpcionesLayout.setVerticalGroup(
            listarObjetoPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listarObjetoPanelOpcionesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(cancelarButton)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        Menu.add(listarObjetoPanelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 240, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JPanel listarObjetoPanel;
    private javax.swing.JPanel listarObjetoPanelOpciones;
    private javax.swing.JPanel listarObjetoPanelTitulo;
    private javax.swing.JTextField nombreDelObjetoTextField;
    private javax.swing.JLabel registrarObjetoPerdidoLabel;
    // End of variables declaration//GEN-END:variables
}
