/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemadeobjetosperdidos;

/**
 *
 * @author ASUS
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        PanelSistemaTitulo = new javax.swing.JPanel();
        LabelSistemaDeObjetosPerdidos = new javax.swing.JLabel();
        PanelSistemaOpciones = new javax.swing.JPanel();
        Button1 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        PanelSistemaSalir = new javax.swing.JPanel();
        ButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setBackground(new java.awt.Color(204, 204, 204));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelSistemaDeObjetosPerdidos.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LabelSistemaDeObjetosPerdidos.setForeground(new java.awt.Color(255, 255, 255));
        LabelSistemaDeObjetosPerdidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSistemaDeObjetosPerdidos.setText("SISTEMA OBJETOS PERDIDOS");
        LabelSistemaDeObjetosPerdidos.setToolTipText("");
        LabelSistemaDeObjetosPerdidos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout PanelSistemaTituloLayout = new javax.swing.GroupLayout(PanelSistemaTitulo);
        PanelSistemaTitulo.setLayout(PanelSistemaTituloLayout);
        PanelSistemaTituloLayout.setHorizontalGroup(
            PanelSistemaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(PanelSistemaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelSistemaTituloLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LabelSistemaDeObjetosPerdidos, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PanelSistemaTituloLayout.setVerticalGroup(
            PanelSistemaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(PanelSistemaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelSistemaTituloLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LabelSistemaDeObjetosPerdidos)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Menu.add(PanelSistemaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 120));

        PanelSistemaOpciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Button1.setText("1.- Registrar Objeto Perdido");
        Button1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Button1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Button1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                Button1ComponentAdded(evt);
            }
        });
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        Button2.setText("2.- Buscar por Código");
        Button2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Button2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });

        Button3.setText("3.- Buscar por Categoría");
        Button3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Button3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        Button4.setText("4.- Listar Objetos");
        Button4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Button4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        Button5.setText("5.- Reclamar Objeto");
        Button5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Button5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout PanelSistemaOpcionesLayout = new javax.swing.GroupLayout(PanelSistemaOpciones);
        PanelSistemaOpciones.setLayout(PanelSistemaOpcionesLayout);
        PanelSistemaOpcionesLayout.setHorizontalGroup(
            PanelSistemaOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSistemaOpcionesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(PanelSistemaOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button1)
                    .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        PanelSistemaOpcionesLayout.setVerticalGroup(
            PanelSistemaOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSistemaOpcionesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Button1)
                .addGap(13, 13, 13)
                .addComponent(Button2)
                .addGap(13, 13, 13)
                .addComponent(Button3)
                .addGap(13, 13, 13)
                .addComponent(Button4)
                .addGap(13, 13, 13)
                .addComponent(Button5)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        Menu.add(PanelSistemaOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 260, 260));

        PanelSistemaSalir.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ButtonSalir.setText("Salir");

        javax.swing.GroupLayout PanelSistemaSalirLayout = new javax.swing.GroupLayout(PanelSistemaSalir);
        PanelSistemaSalir.setLayout(PanelSistemaSalirLayout);
        PanelSistemaSalirLayout.setHorizontalGroup(
            PanelSistemaSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
            .addGroup(PanelSistemaSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelSistemaSalirLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(ButtonSalir)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        PanelSistemaSalirLayout.setVerticalGroup(
            PanelSistemaSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
            .addGroup(PanelSistemaSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelSistemaSalirLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(ButtonSalir)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );

        Menu.add(PanelSistemaSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 110, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_Button1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Button1ComponentAdded

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.JLabel LabelSistemaDeObjetosPerdidos;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel PanelSistemaOpciones;
    private javax.swing.JPanel PanelSistemaSalir;
    private javax.swing.JPanel PanelSistemaTitulo;
    // End of variables declaration//GEN-END:variables
}
