/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemadeobjetosperdidos;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author ASUS
 */
public class Menu extends javax.swing.JFrame {
  

    /**
     * Creates new form menu
     */
    public Menu() {
        setUndecorated(true);
        initComponents();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        SistemaDeObjetosPerdidosPanelTitulo = new javax.swing.JPanel();
        SistemaDeObjetosPerdidosPanelOpciones = new javax.swing.JPanel();
        registrarObjetoPerdidoButton = new javax.swing.JButton();
        buscarPorCategoriaButton = new javax.swing.JButton();
        buscarPorCodigoButton = new javax.swing.JButton();
        listarObjetoButton = new javax.swing.JButton();
        reclamarObjetoButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setBackground(new java.awt.Color(0, 0, 0));
        Menu.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        Menu.setPreferredSize(new java.awt.Dimension(500, 700));
        Menu.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                MenuComponentShown(evt);
            }
        });
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SistemaDeObjetosPerdidosPanelTitulo.setBackground(new java.awt.Color(0, 0, 0));
        SistemaDeObjetosPerdidosPanelTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), " SISTEMA OBJETOS PERDIDOS ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        SistemaDeObjetosPerdidosPanelTitulo.setFocusCycleRoot(true);
        SistemaDeObjetosPerdidosPanelTitulo.setFocusable(false);
        SistemaDeObjetosPerdidosPanelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SistemaDeObjetosPerdidosPanelOpciones.setBackground(new java.awt.Color(0, 0, 0));
        SistemaDeObjetosPerdidosPanelOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), " OPCIONES: ", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        registrarObjetoPerdidoButton.setBackground(new java.awt.Color(0, 0, 0));
        registrarObjetoPerdidoButton.setForeground(new java.awt.Color(255, 255, 255));
        registrarObjetoPerdidoButton.setText("   1.- Registrar Objeto Perdido");
        registrarObjetoPerdidoButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        registrarObjetoPerdidoButton.setFocusPainted(false);
        registrarObjetoPerdidoButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        registrarObjetoPerdidoButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        registrarObjetoPerdidoButton.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                registrarObjetoPerdidoButtonComponentAdded(evt);
            }
        });
        registrarObjetoPerdidoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarObjetoPerdidoButtonActionPerformed(evt);
            }
        });

        buscarPorCategoriaButton.setBackground(new java.awt.Color(0, 0, 0));
        buscarPorCategoriaButton.setForeground(new java.awt.Color(255, 255, 255));
        buscarPorCategoriaButton.setText("   3.- Buscar por Categoría");
        buscarPorCategoriaButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        buscarPorCategoriaButton.setFocusPainted(false);
        buscarPorCategoriaButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buscarPorCategoriaButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        buscarPorCategoriaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPorCategoriaButtonActionPerformed(evt);
            }
        });

        buscarPorCodigoButton.setBackground(new java.awt.Color(0, 0, 0));
        buscarPorCodigoButton.setForeground(new java.awt.Color(255, 255, 255));
        buscarPorCodigoButton.setText("   2.- Buscar por Código");
        buscarPorCodigoButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        buscarPorCodigoButton.setFocusPainted(false);
        buscarPorCodigoButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buscarPorCodigoButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        buscarPorCodigoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPorCodigoButtonActionPerformed(evt);
            }
        });

        listarObjetoButton.setBackground(new java.awt.Color(0, 0, 0));
        listarObjetoButton.setForeground(new java.awt.Color(255, 255, 255));
        listarObjetoButton.setText("   4.- Listar Objetos");
        listarObjetoButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        listarObjetoButton.setFocusPainted(false);
        listarObjetoButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        listarObjetoButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        listarObjetoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarObjetoButtonActionPerformed(evt);
            }
        });

        reclamarObjetoButton.setBackground(new java.awt.Color(0, 0, 0));
        reclamarObjetoButton.setForeground(new java.awt.Color(255, 255, 255));
        reclamarObjetoButton.setText("   5.- Reclamar Objeto");
        reclamarObjetoButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        reclamarObjetoButton.setFocusPainted(false);
        reclamarObjetoButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reclamarObjetoButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        reclamarObjetoButton.setMaximumSize(new java.awt.Dimension(103, 20));
        reclamarObjetoButton.setMinimumSize(new java.awt.Dimension(103, 20));
        reclamarObjetoButton.setPreferredSize(new java.awt.Dimension(103, 20));
        reclamarObjetoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reclamarObjetoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SistemaDeObjetosPerdidosPanelOpcionesLayout = new javax.swing.GroupLayout(SistemaDeObjetosPerdidosPanelOpciones);
        SistemaDeObjetosPerdidosPanelOpciones.setLayout(SistemaDeObjetosPerdidosPanelOpcionesLayout);
        SistemaDeObjetosPerdidosPanelOpcionesLayout.setHorizontalGroup(
            SistemaDeObjetosPerdidosPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SistemaDeObjetosPerdidosPanelOpcionesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(SistemaDeObjetosPerdidosPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reclamarObjetoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listarObjetoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscarPorCategoriaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscarPorCodigoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registrarObjetoPerdidoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        SistemaDeObjetosPerdidosPanelOpcionesLayout.setVerticalGroup(
            SistemaDeObjetosPerdidosPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SistemaDeObjetosPerdidosPanelOpcionesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(registrarObjetoPerdidoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buscarPorCodigoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buscarPorCategoriaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listarObjetoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reclamarObjetoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        SistemaDeObjetosPerdidosPanelTitulo.add(SistemaDeObjetosPerdidosPanelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 380, 490));

        salirButton.setBackground(new java.awt.Color(0, 0, 0));
        salirButton.setForeground(new java.awt.Color(255, 255, 255));
        salirButton.setText("Salir");
        salirButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        salirButton.setFocusPainted(false);
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });
        SistemaDeObjetosPerdidosPanelTitulo.add(salirButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 260, 30));

        Menu.add(SistemaDeObjetosPerdidosPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 440, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reclamarObjetoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reclamarObjetoButtonActionPerformed

        Reclamar reclamar = new Reclamar();
        reclamar.setVisible(true);
        reclamar.setLocationRelativeTo(null);

        // TODO add your handling code here:
    }//GEN-LAST:event_reclamarObjetoButtonActionPerformed

    private void listarObjetoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarObjetoButtonActionPerformed

        ListarJFrame listar = new ListarJFrame();
        listar.setVisible(true);
        listar.setLocationRelativeTo(null);

        // TODO add your handling code here:
    }//GEN-LAST:event_listarObjetoButtonActionPerformed

    private void buscarPorCodigoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPorCodigoButtonActionPerformed

        Busqueda1 busqueda1 = new Busqueda1();
        busqueda1.setVisible(true);
        busqueda1.setLocationRelativeTo(null);

        // TODO add your handling code here:
    }//GEN-LAST:event_buscarPorCodigoButtonActionPerformed

    private void registrarObjetoPerdidoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarObjetoPerdidoButtonActionPerformed

        RegistroJFrame registro = new RegistroJFrame();
        registro.setVisible(true);
        registro.setLocationRelativeTo(null);

        // TODO add your handling code here:

    }//GEN-LAST:event_registrarObjetoPerdidoButtonActionPerformed

    private void registrarObjetoPerdidoButtonComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_registrarObjetoPerdidoButtonComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarObjetoPerdidoButtonComponentAdded

    private void buscarPorCategoriaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPorCategoriaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarPorCategoriaButtonActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        
        System.exit(0);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_salirButtonActionPerformed

    private void MenuComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_MenuComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuComponentShown

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel SistemaDeObjetosPerdidosPanelOpciones;
    private javax.swing.JPanel SistemaDeObjetosPerdidosPanelTitulo;
    private javax.swing.JButton buscarPorCategoriaButton;
    private javax.swing.JButton buscarPorCodigoButton;
    private javax.swing.JButton listarObjetoButton;
    private javax.swing.JButton reclamarObjetoButton;
    private javax.swing.JButton registrarObjetoPerdidoButton;
    private javax.swing.JButton salirButton;
    // End of variables declaration//GEN-END:variables
}
