/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemadeobjetosperdidos;

/**
 *
 * @author ASUS
 */
public class reclamar extends javax.swing.JFrame {

    /**
     * Creates new form reclamar
     */
    public reclamar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        reclamarObjetoPanelTitulo = new javax.swing.JPanel();
        reclamarObjetoLabel = new javax.swing.JLabel();
        reclamarObjetoPanelBusqueda = new javax.swing.JPanel();
        IDLabel = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        mostrarInformacionTextField = new javax.swing.JTextField();
        reclamarObjetoPanelOpciones1 = new javax.swing.JPanel();
        confirmarCancelarObjetoLabel = new javax.swing.JLabel();
        confirmarButton = new javax.swing.JButton();
        cancelarButton1 = new javax.swing.JButton();
        reclamarObjetoPanel = new javax.swing.JPanel();
        reclamanteLabel = new javax.swing.JLabel();
        reclamanteTextField = new javax.swing.JTextField();
        codigoDelReclamanteLabel = new javax.swing.JLabel();
        codigoDelReclamanteTextField = new javax.swing.JTextField();
        correoDelReclamanteLabel = new javax.swing.JLabel();
        correoDelReclamanteTextField = new javax.swing.JTextField();
        telefonoDelReclamanteLabel = new javax.swing.JLabel();
        telefonoDelReclamanteTextField = new javax.swing.JTextField();
        reclamarObjetoPanelOpciones2 = new javax.swing.JPanel();
        aceptarButton = new javax.swing.JButton();
        cancelarButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setBackground(new java.awt.Color(204, 204, 204));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reclamarObjetoLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        reclamarObjetoLabel.setForeground(new java.awt.Color(255, 255, 255));
        reclamarObjetoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reclamarObjetoLabel.setText("REGISTRO DE OBJETOS PERDIDOS");
        reclamarObjetoLabel.setToolTipText("");
        reclamarObjetoLabel.setAutoscrolls(true);

        javax.swing.GroupLayout reclamarObjetoPanelTituloLayout = new javax.swing.GroupLayout(reclamarObjetoPanelTitulo);
        reclamarObjetoPanelTitulo.setLayout(reclamarObjetoPanelTituloLayout);
        reclamarObjetoPanelTituloLayout.setHorizontalGroup(
            reclamarObjetoPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reclamarObjetoPanelTituloLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(reclamarObjetoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        reclamarObjetoPanelTituloLayout.setVerticalGroup(
            reclamarObjetoPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reclamarObjetoPanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reclamarObjetoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        Menu.add(reclamarObjetoPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 120));

        reclamarObjetoPanelBusqueda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        IDLabel.setText("INGRESE EL ID DEL OBJETO A RECLAMAR:");

        IDTextField.setForeground(new java.awt.Color(102, 102, 102));
        IDTextField.setText("Ejm: 1, 2, 3,...");
        IDTextField.setToolTipText("");
        IDTextField.setCaretColor(new java.awt.Color(102, 102, 102));

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        mostrarInformacionTextField.setForeground(new java.awt.Color(102, 102, 102));
        mostrarInformacionTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mostrarInformacionTextField.setActionCommand("<Not Set>");
        mostrarInformacionTextField.setCaretColor(new java.awt.Color(102, 102, 102));
        mostrarInformacionTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        mostrarInformacionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarInformacionTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reclamarObjetoPanelBusquedaLayout = new javax.swing.GroupLayout(reclamarObjetoPanelBusqueda);
        reclamarObjetoPanelBusqueda.setLayout(reclamarObjetoPanelBusquedaLayout);
        reclamarObjetoPanelBusquedaLayout.setHorizontalGroup(
            reclamarObjetoPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reclamarObjetoPanelBusquedaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(reclamarObjetoPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(reclamarObjetoPanelBusquedaLayout.createSequentialGroup()
                        .addGroup(reclamarObjetoPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDLabel)
                            .addGroup(reclamarObjetoPanelBusquedaLayout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(buscarButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDTextField))
                    .addComponent(mostrarInformacionTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        reclamarObjetoPanelBusquedaLayout.setVerticalGroup(
            reclamarObjetoPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reclamarObjetoPanelBusquedaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(reclamarObjetoPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDLabel)
                    .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarInformacionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        Menu.add(reclamarObjetoPanelBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 380, 400));

        reclamarObjetoPanelOpciones1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        confirmarCancelarObjetoLabel.setText("ES EL OBJETO CORRECTO??");

        confirmarButton.setText("Confirmar");
        confirmarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarButtonActionPerformed(evt);
            }
        });

        cancelarButton1.setText("Cancelar");
        cancelarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reclamarObjetoPanelOpciones1Layout = new javax.swing.GroupLayout(reclamarObjetoPanelOpciones1);
        reclamarObjetoPanelOpciones1.setLayout(reclamarObjetoPanelOpciones1Layout);
        reclamarObjetoPanelOpciones1Layout.setHorizontalGroup(
            reclamarObjetoPanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reclamarObjetoPanelOpciones1Layout.createSequentialGroup()
                .addGroup(reclamarObjetoPanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reclamarObjetoPanelOpciones1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(confirmarButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelarButton1))
                    .addGroup(reclamarObjetoPanelOpciones1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(confirmarCancelarObjetoLabel)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        reclamarObjetoPanelOpciones1Layout.setVerticalGroup(
            reclamarObjetoPanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reclamarObjetoPanelOpciones1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(confirmarCancelarObjetoLabel)
                .addGap(18, 18, 18)
                .addGroup(reclamarObjetoPanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton1)
                    .addComponent(confirmarButton))
                .addGap(27, 27, 27))
        );

        Menu.add(reclamarObjetoPanelOpciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, 240, 120));

        reclamarObjetoPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        reclamanteLabel.setText("NOMBRES COMPLETOS DEL RECLAMANTE");

        reclamanteTextField.setForeground(new java.awt.Color(102, 102, 102));
        reclamanteTextField.setText("Ejm: Laptop, Pomo, Gorra, etc.");
        reclamanteTextField.setToolTipText("");
        reclamanteTextField.setCaretColor(new java.awt.Color(102, 102, 102));

        codigoDelReclamanteLabel.setText("CODIGO DE ESTUDIANTE DEL RECLAMANTE");

        codigoDelReclamanteTextField.setForeground(new java.awt.Color(102, 102, 102));
        codigoDelReclamanteTextField.setText("Ejm: Laptop, Pomo, Gorra, etc.");
        codigoDelReclamanteTextField.setToolTipText("");
        codigoDelReclamanteTextField.setCaretColor(new java.awt.Color(102, 102, 102));

        correoDelReclamanteLabel.setText("CORREO DEL RECLAMANTE");

        correoDelReclamanteTextField.setForeground(new java.awt.Color(102, 102, 102));
        correoDelReclamanteTextField.setText("Ejm: Laptop, Pomo, Gorra, etc.");
        correoDelReclamanteTextField.setToolTipText("");
        correoDelReclamanteTextField.setCaretColor(new java.awt.Color(102, 102, 102));

        telefonoDelReclamanteLabel.setText("TELEFONO DEL RECLAMANTE");

        telefonoDelReclamanteTextField.setForeground(new java.awt.Color(102, 102, 102));
        telefonoDelReclamanteTextField.setText("Ejm: Laptop, Pomo, Gorra, etc.");
        telefonoDelReclamanteTextField.setToolTipText("");
        telefonoDelReclamanteTextField.setCaretColor(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout reclamarObjetoPanelLayout = new javax.swing.GroupLayout(reclamarObjetoPanel);
        reclamarObjetoPanel.setLayout(reclamarObjetoPanelLayout);
        reclamarObjetoPanelLayout.setHorizontalGroup(
            reclamarObjetoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reclamarObjetoPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(reclamarObjetoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(correoDelReclamanteLabel)
                    .addComponent(codigoDelReclamanteLabel)
                    .addComponent(telefonoDelReclamanteLabel)
                    .addComponent(reclamanteTextField)
                    .addComponent(codigoDelReclamanteTextField)
                    .addComponent(telefonoDelReclamanteTextField)
                    .addComponent(correoDelReclamanteTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(reclamanteLabel))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        reclamarObjetoPanelLayout.setVerticalGroup(
            reclamarObjetoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reclamarObjetoPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(reclamanteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reclamanteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(codigoDelReclamanteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigoDelReclamanteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(correoDelReclamanteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(correoDelReclamanteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(telefonoDelReclamanteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefonoDelReclamanteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );

        Menu.add(reclamarObjetoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 380, 310));

        reclamarObjetoPanelOpciones2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        cancelarButton2.setText("Cancelar");
        cancelarButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reclamarObjetoPanelOpciones2Layout = new javax.swing.GroupLayout(reclamarObjetoPanelOpciones2);
        reclamarObjetoPanelOpciones2.setLayout(reclamarObjetoPanelOpciones2Layout);
        reclamarObjetoPanelOpciones2Layout.setHorizontalGroup(
            reclamarObjetoPanelOpciones2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reclamarObjetoPanelOpciones2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(aceptarButton)
                .addGap(18, 18, 18)
                .addComponent(cancelarButton2)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        reclamarObjetoPanelOpciones2Layout.setVerticalGroup(
            reclamarObjetoPanelOpciones2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reclamarObjetoPanelOpciones2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(reclamarObjetoPanelOpciones2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton2)
                    .addComponent(aceptarButton))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Menu.add(reclamarObjetoPanelOpciones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1020, 240, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 1117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void cancelarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarButton2ActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void mostrarInformacionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarInformacionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarInformacionTextFieldActionPerformed

    private void confirmarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmarButtonActionPerformed

    private void cancelarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reclamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reclamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reclamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reclamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reclamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton buscarButton;
    private javax.swing.JButton cancelarButton1;
    private javax.swing.JButton cancelarButton2;
    private javax.swing.JLabel codigoDelReclamanteLabel;
    private javax.swing.JTextField codigoDelReclamanteTextField;
    private javax.swing.JButton confirmarButton;
    private javax.swing.JLabel confirmarCancelarObjetoLabel;
    private javax.swing.JLabel correoDelReclamanteLabel;
    private javax.swing.JTextField correoDelReclamanteTextField;
    private javax.swing.JTextField mostrarInformacionTextField;
    private javax.swing.JLabel reclamanteLabel;
    private javax.swing.JTextField reclamanteTextField;
    private javax.swing.JLabel reclamarObjetoLabel;
    private javax.swing.JPanel reclamarObjetoPanel;
    private javax.swing.JPanel reclamarObjetoPanelBusqueda;
    private javax.swing.JPanel reclamarObjetoPanelOpciones1;
    private javax.swing.JPanel reclamarObjetoPanelOpciones2;
    private javax.swing.JPanel reclamarObjetoPanelTitulo;
    private javax.swing.JLabel telefonoDelReclamanteLabel;
    private javax.swing.JTextField telefonoDelReclamanteTextField;
    // End of variables declaration//GEN-END:variables
}
