/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemadeobjetosperdidos;

import static com.mycompany.sistemadeobjetosperdidos.ObjetoDAO.cargarObjetos;
import java.awt.Color;

/**
 *
 * @author ASUS
 */
public class ReclamarJFrame extends javax.swing.JFrame {

    /**
     * Creates new form reclamar
     */
    public ReclamarJFrame() {
        setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        reclamarObjetoPanelBusqueda = new javax.swing.JPanel();
        IDTextField = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrarInformacionTextArea = new javax.swing.JTextArea();
        reclamarObjetoPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        reclamanteTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        codigoDelReclamanteTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        correoDelReclamanteTextField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        telefonoDelReclamanteTextField = new javax.swing.JTextField();
        aceptarButton = new javax.swing.JButton();
        cancelarButton2 = new javax.swing.JButton();

        jPanel6.setPreferredSize(new java.awt.Dimension(500, 1150));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1157, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(500, 700));
        setMinimumSize(new java.awt.Dimension(500, 700));
        setPreferredSize(new java.awt.Dimension(500, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 700));

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setHorizontalScrollBar(null);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(500, 1168));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 1168));

        menu.setBackground(new java.awt.Color(0, 0, 0));
        menu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), " RECLAMAR OBJETO ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        menu.setForeground(new java.awt.Color(255, 255, 255));
        menu.setPreferredSize(new java.awt.Dimension(450, 1068));

        reclamarObjetoPanelBusqueda.setBackground(new java.awt.Color(0, 0, 0));
        reclamarObjetoPanelBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), " INGRESE EL ID DEL OBJETO A RECLAMAR:    ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        IDTextField.setBackground(new java.awt.Color(0, 0, 0));
        IDTextField.setForeground(java.awt.Color.gray);
        IDTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IDTextField.setText("Ejm: 1, 2, 3,...");
        IDTextField.setToolTipText("");
        IDTextField.setBorder(null);
        IDTextField.setCaretColor(new java.awt.Color(102, 102, 102));
        IDTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDTextFieldFocusLost(evt);
            }
        });
        IDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reclamarObjetoPanelBusquedaLayout = new javax.swing.GroupLayout(reclamarObjetoPanelBusqueda);
        reclamarObjetoPanelBusqueda.setLayout(reclamarObjetoPanelBusquedaLayout);
        reclamarObjetoPanelBusquedaLayout.setHorizontalGroup(
            reclamarObjetoPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reclamarObjetoPanelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );
        reclamarObjetoPanelBusquedaLayout.setVerticalGroup(
            reclamarObjetoPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reclamarObjetoPanelBusquedaLayout.createSequentialGroup()
                .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        buscarButton.setBackground(new java.awt.Color(0, 0, 0));
        buscarButton.setForeground(new java.awt.Color(255, 255, 255));
        buscarButton.setText("Buscar");
        buscarButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        buscarButton.setFocusPainted(false);
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);

        mostrarInformacionTextArea.setBackground(new java.awt.Color(0, 0, 0));
        mostrarInformacionTextArea.setColumns(20);
        mostrarInformacionTextArea.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        mostrarInformacionTextArea.setForeground(new java.awt.Color(255, 255, 255));
        mostrarInformacionTextArea.setRows(5);
        mostrarInformacionTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), " INFORMACION DEL OBJETO   ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jScrollPane1.setViewportView(mostrarInformacionTextArea);

        reclamarObjetoPanel.setBackground(new java.awt.Color(0, 0, 0));
        reclamarObjetoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), " REGISTRO DEL RECLAMANTE    ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        reclamarObjetoPanel.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), " NOMBRES COMPLETOS DEL RECLAMANTE:    ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        reclamanteTextField.setBackground(new java.awt.Color(0, 0, 0));
        reclamanteTextField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        reclamanteTextField.setForeground(java.awt.Color.gray);
        reclamanteTextField.setText("Nombres y apellidos");
        reclamanteTextField.setToolTipText("");
        reclamanteTextField.setBorder(null);
        reclamanteTextField.setCaretColor(new java.awt.Color(102, 102, 102));
        reclamanteTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                reclamanteTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                reclamanteTextFieldFocusLost(evt);
            }
        });
        reclamanteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reclamanteTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reclamanteTextField)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reclamanteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), " CODIGO DE ESTUDIANTE DEL RECLAMANTE:    ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        codigoDelReclamanteTextField.setBackground(new java.awt.Color(0, 0, 0));
        codigoDelReclamanteTextField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        codigoDelReclamanteTextField.setForeground(java.awt.Color.gray);
        codigoDelReclamanteTextField.setText("251108....");
        codigoDelReclamanteTextField.setToolTipText("");
        codigoDelReclamanteTextField.setBorder(null);
        codigoDelReclamanteTextField.setCaretColor(new java.awt.Color(102, 102, 102));
        codigoDelReclamanteTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codigoDelReclamanteTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigoDelReclamanteTextFieldFocusLost(evt);
            }
        });
        codigoDelReclamanteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoDelReclamanteTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(codigoDelReclamanteTextField)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(codigoDelReclamanteTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), " CORREO DEL RECLAMANTE:   ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        correoDelReclamanteTextField.setBackground(new java.awt.Color(0, 0, 0));
        correoDelReclamanteTextField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        correoDelReclamanteTextField.setForeground(java.awt.Color.gray);
        correoDelReclamanteTextField.setText("noreply@email.com");
        correoDelReclamanteTextField.setToolTipText("");
        correoDelReclamanteTextField.setBorder(null);
        correoDelReclamanteTextField.setCaretColor(new java.awt.Color(102, 102, 102));
        correoDelReclamanteTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                correoDelReclamanteTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                correoDelReclamanteTextFieldFocusLost(evt);
            }
        });
        correoDelReclamanteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoDelReclamanteTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(correoDelReclamanteTextField)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(correoDelReclamanteTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), " TELEFONO DEL RECLAMANTE:    ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        telefonoDelReclamanteTextField.setBackground(new java.awt.Color(0, 0, 0));
        telefonoDelReclamanteTextField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        telefonoDelReclamanteTextField.setForeground(java.awt.Color.gray);
        telefonoDelReclamanteTextField.setText("919145897");
        telefonoDelReclamanteTextField.setToolTipText("");
        telefonoDelReclamanteTextField.setBorder(null);
        telefonoDelReclamanteTextField.setCaretColor(new java.awt.Color(102, 102, 102));
        telefonoDelReclamanteTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefonoDelReclamanteTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefonoDelReclamanteTextFieldFocusLost(evt);
            }
        });
        telefonoDelReclamanteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoDelReclamanteTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telefonoDelReclamanteTextField)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telefonoDelReclamanteTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout reclamarObjetoPanelLayout = new javax.swing.GroupLayout(reclamarObjetoPanel);
        reclamarObjetoPanel.setLayout(reclamarObjetoPanelLayout);
        reclamarObjetoPanelLayout.setHorizontalGroup(
            reclamarObjetoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reclamarObjetoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reclamarObjetoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        reclamarObjetoPanelLayout.setVerticalGroup(
            reclamarObjetoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reclamarObjetoPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        aceptarButton.setBackground(new java.awt.Color(0, 0, 0));
        aceptarButton.setForeground(new java.awt.Color(255, 255, 255));
        aceptarButton.setText("Aceptar");
        aceptarButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        aceptarButton.setFocusPainted(false);
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        cancelarButton2.setBackground(new java.awt.Color(0, 0, 0));
        cancelarButton2.setForeground(new java.awt.Color(255, 255, 255));
        cancelarButton2.setText("Cancelar");
        cancelarButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        cancelarButton2.setFocusPainted(false);
        cancelarButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(aceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelarButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(reclamarObjetoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(reclamarObjetoPanelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(reclamarObjetoPanelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(reclamarObjetoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1157, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed


        
        String[] objeto = Objeto.getLista().get(Integer.parseInt(IDTextField.getText())-1);
        
        mostrarInformacionTextArea.setText("");
        
        mostrarInformacionTextArea.append("\n");
        mostrarInformacionTextArea.append(" ------- INFORMACION DEL OBJETO ---------------------\n ");
        mostrarInformacionTextArea.append("\n");
        mostrarInformacionTextArea.append(" - NOMBRE DEL OBJETO: "+ objeto[1]+"\n");
        mostrarInformacionTextArea.append(" - DESCRIPCION: "+ objeto[2]+"\n");
        mostrarInformacionTextArea.append(" - CATEGORIA: "+ objeto[3]+"\n");
        mostrarInformacionTextArea.append(" - LUGAR Y FEHCA: "+ objeto[4]+"\n");
        mostrarInformacionTextArea.append(" - REPORTANTE: "+ objeto[5]+"\n");
        mostrarInformacionTextArea.append(" - ESTADO DEL OBJETO: "+ objeto[6]+"\n");
        mostrarInformacionTextArea.append("\n");
        
        mostrarInformacionTextArea.append("  ------- INFORMACION DEL RECLAMANTE ---------------------\n ");
        mostrarInformacionTextArea.append("\n");
        mostrarInformacionTextArea.append(" - NOMBRE DEL RECLAMANTE: "+ objeto[7]+"\n");
        mostrarInformacionTextArea.append(" - CODIGO DEL RECLAMANTE: "+ objeto[8]+"\n");
        mostrarInformacionTextArea.append(" - CORREO DEL RECLAMANTE: "+ objeto[9]+"\n");
        mostrarInformacionTextArea.append(" - TELEFONO DEL RECLAMANTE: "+ objeto[10]+"\n");  
        mostrarInformacionTextArea.append("\n");

        // TODO add your handling code here:
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void cancelarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButton2ActionPerformed

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarButton2ActionPerformed

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed

        String idDeBusqueda =IDTextField.getText();
        
        String reclamante = reclamanteTextField.getText();
        reclamante = reclamante.substring(0, 1).toUpperCase() + reclamante.substring(1).toLowerCase();

        String codigoDelReclamante = codigoDelReclamanteTextField.getText();
        codigoDelReclamante= codigoDelReclamante.substring(0, 1).toUpperCase() + codigoDelReclamante.substring(1).toLowerCase();

        String correoDelReclamante = correoDelReclamanteTextField.getText();
        correoDelReclamante = correoDelReclamante.substring(0, 1).toUpperCase() + correoDelReclamante.substring(1).toLowerCase();

        String telefonoDelReclamante = telefonoDelReclamanteTextField.getText();
        telefonoDelReclamante = telefonoDelReclamante.substring(0, 1).toUpperCase() + telefonoDelReclamante.substring(1).toLowerCase();
        
        String[] RegistroReclamarObjeto = {"RECLAMADO",reclamante,codigoDelReclamante,correoDelReclamante,telefonoDelReclamante, idDeBusqueda};
        
        ObjetoDAO.reclamarObjeto(RegistroReclamarObjeto);

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void telefonoDelReclamanteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoDelReclamanteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoDelReclamanteTextFieldActionPerformed

    private void correoDelReclamanteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoDelReclamanteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoDelReclamanteTextFieldActionPerformed

    private void IDTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDTextFieldFocusGained

        if (IDTextField.getText().equals("Ejm: 1, 2, 3,... ")) {
            
            IDTextField.setText("");
            IDTextField.setForeground(Color.WHITE);
                    
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextFieldFocusGained

    private void IDTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDTextFieldFocusLost

        if (IDTextField.getText().isEmpty()) {
            
            IDTextField.setText("Ejm: 1, 2, 3,... ");
            IDTextField.setForeground(Color.GRAY);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextFieldFocusLost

    private void reclamanteTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reclamanteTextFieldFocusGained

            
        if (reclamanteTextField.getText().equals("Nombres y apellidos")) {
            
            reclamanteTextField.setText("");
            reclamanteTextField.setForeground(Color.WHITE);
                    
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_reclamanteTextFieldFocusGained

    private void reclamanteTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reclamanteTextFieldFocusLost

        if (reclamanteTextField.getText().isEmpty()) {
            
            reclamanteTextField.setText("Nombres y apellidos");
            reclamanteTextField.setForeground(Color.GRAY);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_reclamanteTextFieldFocusLost

    private void codigoDelReclamanteTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoDelReclamanteTextFieldFocusGained

        if (codigoDelReclamanteTextField.getText().equals("251108....")) {
            
            codigoDelReclamanteTextField.setText("");
            codigoDelReclamanteTextField.setForeground(Color.WHITE);
                    
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_codigoDelReclamanteTextFieldFocusGained

    private void codigoDelReclamanteTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoDelReclamanteTextFieldFocusLost

        if (codigoDelReclamanteTextField.getText().isEmpty()) {
            
            codigoDelReclamanteTextField.setText("251108....");
            codigoDelReclamanteTextField.setForeground(Color.GRAY);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_codigoDelReclamanteTextFieldFocusLost

    private void correoDelReclamanteTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correoDelReclamanteTextFieldFocusGained

        if (correoDelReclamanteTextField.getText().equals("noreply@email.com")) {
            
            correoDelReclamanteTextField.setText("");
            correoDelReclamanteTextField.setForeground(Color.WHITE);
                    
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_correoDelReclamanteTextFieldFocusGained

    private void correoDelReclamanteTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correoDelReclamanteTextFieldFocusLost

        if (correoDelReclamanteTextField.getText().isEmpty()) {
            
            correoDelReclamanteTextField.setText("noreply@email.com");
            correoDelReclamanteTextField.setForeground(Color.GRAY);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_correoDelReclamanteTextFieldFocusLost

    private void telefonoDelReclamanteTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoDelReclamanteTextFieldFocusGained

        if (telefonoDelReclamanteTextField.getText().equals("919145897")) {
            
            telefonoDelReclamanteTextField.setText("");
            telefonoDelReclamanteTextField.setForeground(Color.WHITE);
                    
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoDelReclamanteTextFieldFocusGained

    private void telefonoDelReclamanteTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoDelReclamanteTextFieldFocusLost

        if (telefonoDelReclamanteTextField.getText().isEmpty()) {
            
            telefonoDelReclamanteTextField.setText("919145897");
            telefonoDelReclamanteTextField.setForeground(Color.GRAY);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoDelReclamanteTextFieldFocusLost

    private void codigoDelReclamanteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoDelReclamanteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoDelReclamanteTextFieldActionPerformed

    private void reclamanteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reclamanteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reclamanteTextFieldActionPerformed

    private void IDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDTextField;
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton buscarButton;
    private javax.swing.JButton cancelarButton2;
    private javax.swing.JTextField codigoDelReclamanteTextField;
    private javax.swing.JTextField correoDelReclamanteTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel menu;
    private javax.swing.JTextArea mostrarInformacionTextArea;
    private javax.swing.JTextField reclamanteTextField;
    private javax.swing.JPanel reclamarObjetoPanel;
    private javax.swing.JPanel reclamarObjetoPanelBusqueda;
    private javax.swing.JTextField telefonoDelReclamanteTextField;
    // End of variables declaration//GEN-END:variables
}
