/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemadeobjetosperdidos;

import java.awt.Color;

/**
 *
 * @author ASUS
 */
public class RegistroJFrame extends javax.swing.JFrame {

    /**
     * Creates new form registro
     */
    public RegistroJFrame() {
        
        
        setUndecorated(true);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        registrarObjetoPerdidoPanelTitulo = new javax.swing.JPanel();
        registrarObjetoPerdidoPanel = new javax.swing.JPanel();
        nombreDelObjetoTextField = new javax.swing.JTextField();
        registrarObjetoPerdidoPanel1 = new javax.swing.JPanel();
        descripcionDelObjetoTextField = new javax.swing.JTextField();
        registrarObjetoPerdidoPanel2 = new javax.swing.JPanel();
        categoriaDelObjetoComboBox = new javax.swing.JComboBox<>();
        registrarObjetoPerdidoPanel3 = new javax.swing.JPanel();
        lugarYFechaTextField = new javax.swing.JTextField();
        registrarObjetoPerdidoPanel4 = new javax.swing.JPanel();
        reportanteTextField = new javax.swing.JTextField();
        cancelarButton = new javax.swing.JButton();
        aceptarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setBackground(new java.awt.Color(0, 0, 0));
        Menu.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        Menu.setPreferredSize(new java.awt.Dimension(500, 700));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrarObjetoPerdidoPanelTitulo.setBackground(new java.awt.Color(0, 0, 0));
        registrarObjetoPerdidoPanelTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), " REGISTRO DE OBJETOS PERDIDOS ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        registrarObjetoPerdidoPanel.setBackground(new java.awt.Color(0, 0, 0));
        registrarObjetoPerdidoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), " OBJETO:   ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        nombreDelObjetoTextField.setBackground(new java.awt.Color(0, 0, 0));
        nombreDelObjetoTextField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        nombreDelObjetoTextField.setForeground(java.awt.Color.gray);
        nombreDelObjetoTextField.setText("Gorra...");
        nombreDelObjetoTextField.setBorder(null);
        nombreDelObjetoTextField.setSelectionColor(new java.awt.Color(255, 255, 255));
        nombreDelObjetoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreDelObjetoTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreDelObjetoTextFieldFocusLost(evt);
            }
        });
        nombreDelObjetoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreDelObjetoTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registrarObjetoPerdidoPanelLayout = new javax.swing.GroupLayout(registrarObjetoPerdidoPanel);
        registrarObjetoPerdidoPanel.setLayout(registrarObjetoPerdidoPanelLayout);
        registrarObjetoPerdidoPanelLayout.setHorizontalGroup(
            registrarObjetoPerdidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarObjetoPerdidoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreDelObjetoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );
        registrarObjetoPerdidoPanelLayout.setVerticalGroup(
            registrarObjetoPerdidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nombreDelObjetoTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        registrarObjetoPerdidoPanel1.setBackground(new java.awt.Color(0, 0, 0));
        registrarObjetoPerdidoPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), " DESCRIPCION:   ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        descripcionDelObjetoTextField.setBackground(new java.awt.Color(0, 0, 0));
        descripcionDelObjetoTextField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        descripcionDelObjetoTextField.setForeground(java.awt.Color.gray);
        descripcionDelObjetoTextField.setText("Gorro de color rojo y blanco, con diseño,...");
        descripcionDelObjetoTextField.setBorder(null);
        descripcionDelObjetoTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        descripcionDelObjetoTextField.setSelectionColor(new java.awt.Color(255, 255, 255));
        descripcionDelObjetoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descripcionDelObjetoTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                descripcionDelObjetoTextFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout registrarObjetoPerdidoPanel1Layout = new javax.swing.GroupLayout(registrarObjetoPerdidoPanel1);
        registrarObjetoPerdidoPanel1.setLayout(registrarObjetoPerdidoPanel1Layout);
        registrarObjetoPerdidoPanel1Layout.setHorizontalGroup(
            registrarObjetoPerdidoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarObjetoPerdidoPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descripcionDelObjetoTextField)
                .addContainerGap())
        );
        registrarObjetoPerdidoPanel1Layout.setVerticalGroup(
            registrarObjetoPerdidoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(descripcionDelObjetoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        registrarObjetoPerdidoPanel2.setBackground(new java.awt.Color(0, 0, 0));
        registrarObjetoPerdidoPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), " CATEGORIA:    ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        categoriaDelObjetoComboBox.setBackground(new java.awt.Color(0, 0, 0));
        categoriaDelObjetoComboBox.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        categoriaDelObjetoComboBox.setForeground(java.awt.Color.gray);
        categoriaDelObjetoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoriaDelObjetoComboBox.setBorder(null);
        categoriaDelObjetoComboBox.setFocusable(false);
        categoriaDelObjetoComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                categoriaDelObjetoComboBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout registrarObjetoPerdidoPanel2Layout = new javax.swing.GroupLayout(registrarObjetoPerdidoPanel2);
        registrarObjetoPerdidoPanel2.setLayout(registrarObjetoPerdidoPanel2Layout);
        registrarObjetoPerdidoPanel2Layout.setHorizontalGroup(
            registrarObjetoPerdidoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarObjetoPerdidoPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(categoriaDelObjetoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        registrarObjetoPerdidoPanel2Layout.setVerticalGroup(
            registrarObjetoPerdidoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarObjetoPerdidoPanel2Layout.createSequentialGroup()
                .addComponent(categoriaDelObjetoComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        registrarObjetoPerdidoPanel3.setBackground(new java.awt.Color(0, 0, 0));
        registrarObjetoPerdidoPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), " LUGAR Y FECHA DEL REPORTE:   ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        lugarYFechaTextField.setBackground(new java.awt.Color(0, 0, 0));
        lugarYFechaTextField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lugarYFechaTextField.setForeground(java.awt.Color.gray);
        lugarYFechaTextField.setText("Aula2 - Casa de la Cultura - 12/12/12");
        lugarYFechaTextField.setBorder(null);
        lugarYFechaTextField.setSelectionColor(new java.awt.Color(255, 255, 255));
        lugarYFechaTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lugarYFechaTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lugarYFechaTextFieldFocusLost(evt);
            }
        });
        lugarYFechaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugarYFechaTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registrarObjetoPerdidoPanel3Layout = new javax.swing.GroupLayout(registrarObjetoPerdidoPanel3);
        registrarObjetoPerdidoPanel3.setLayout(registrarObjetoPerdidoPanel3Layout);
        registrarObjetoPerdidoPanel3Layout.setHorizontalGroup(
            registrarObjetoPerdidoPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarObjetoPerdidoPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lugarYFechaTextField)
                .addContainerGap())
        );
        registrarObjetoPerdidoPanel3Layout.setVerticalGroup(
            registrarObjetoPerdidoPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lugarYFechaTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        registrarObjetoPerdidoPanel4.setBackground(new java.awt.Color(0, 0, 0));
        registrarObjetoPerdidoPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), " NOMBRES COMPLETOS DEL REPORTANTE:   ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        reportanteTextField.setBackground(new java.awt.Color(0, 0, 0));
        reportanteTextField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        reportanteTextField.setForeground(java.awt.Color.gray);
        reportanteTextField.setText("Nombres y apellidos");
        reportanteTextField.setBorder(null);
        reportanteTextField.setSelectionColor(new java.awt.Color(255, 255, 255));
        reportanteTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                reportanteTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                reportanteTextFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout registrarObjetoPerdidoPanel4Layout = new javax.swing.GroupLayout(registrarObjetoPerdidoPanel4);
        registrarObjetoPerdidoPanel4.setLayout(registrarObjetoPerdidoPanel4Layout);
        registrarObjetoPerdidoPanel4Layout.setHorizontalGroup(
            registrarObjetoPerdidoPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarObjetoPerdidoPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reportanteTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );
        registrarObjetoPerdidoPanel4Layout.setVerticalGroup(
            registrarObjetoPerdidoPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrarObjetoPerdidoPanel4Layout.createSequentialGroup()
                .addComponent(reportanteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        cancelarButton.setBackground(new java.awt.Color(0, 0, 0));
        cancelarButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelarButton.setText("Cancelar");
        cancelarButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        cancelarButton.setFocusPainted(false);
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        aceptarButton.setBackground(new java.awt.Color(0, 0, 0));
        aceptarButton.setForeground(new java.awt.Color(255, 255, 255));
        aceptarButton.setText("Aceptar");
        aceptarButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        aceptarButton.setFocusPainted(false);
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registrarObjetoPerdidoPanelTituloLayout = new javax.swing.GroupLayout(registrarObjetoPerdidoPanelTitulo);
        registrarObjetoPerdidoPanelTitulo.setLayout(registrarObjetoPerdidoPanelTituloLayout);
        registrarObjetoPerdidoPanelTituloLayout.setHorizontalGroup(
            registrarObjetoPerdidoPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarObjetoPerdidoPanelTituloLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(aceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrarObjetoPerdidoPanelTituloLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(registrarObjetoPerdidoPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registrarObjetoPerdidoPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(registrarObjetoPerdidoPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(registrarObjetoPerdidoPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registrarObjetoPerdidoPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registrarObjetoPerdidoPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registrarObjetoPerdidoPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        registrarObjetoPerdidoPanelTituloLayout.setVerticalGroup(
            registrarObjetoPerdidoPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarObjetoPerdidoPanelTituloLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(registrarObjetoPerdidoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(registrarObjetoPerdidoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registrarObjetoPerdidoPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registrarObjetoPerdidoPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(registrarObjetoPerdidoPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addGroup(registrarObjetoPerdidoPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        Menu.add(registrarObjetoPerdidoPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 440, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        
        String nombreDelObjeto = nombreDelObjetoTextField.getText();
        nombreDelObjeto = nombreDelObjeto.substring(0, 1).toUpperCase() + nombreDelObjeto.substring(1).toLowerCase();

        String descripcionDelObjeto = descripcionDelObjetoTextField.getText();
        descripcionDelObjeto = descripcionDelObjeto.substring(0, 1).toUpperCase() + descripcionDelObjeto.substring(1).toLowerCase();

        String categoriaDelObjeto = categoriaDelObjetoComboBox.getSelectedItem().toString();
        categoriaDelObjeto = categoriaDelObjeto.substring(0, 1).toUpperCase() + categoriaDelObjeto.substring(1).toLowerCase();

        String lugarYFecha = lugarYFechaTextField.getText();
        lugarYFecha = lugarYFecha.substring(0, 1).toUpperCase() + lugarYFecha.substring(1).toLowerCase();
        
        String reportante = reportanteTextField.getText();
        reportante = reportante.substring(0, 1).toUpperCase() + reportante.substring(1).toLowerCase();
        
        Objeto.getLista().add(new String[]{nombreDelObjeto,descripcionDelObjeto,categoriaDelObjeto,lugarYFecha,reportante,"PERDIDO",null,null,null,null});
        
        this.dispose();
        

        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void lugarYFechaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugarYFechaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lugarYFechaTextFieldActionPerformed

    private void nombreDelObjetoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreDelObjetoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreDelObjetoTextFieldActionPerformed

    private void categoriaDelObjetoComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_categoriaDelObjetoComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaDelObjetoComboBoxItemStateChanged

    private void nombreDelObjetoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreDelObjetoTextFieldFocusGained

        if (nombreDelObjetoTextField.getText().equals("Gorra...")) {
            
            nombreDelObjetoTextField.setText("");
            nombreDelObjetoTextField.setForeground(Color.WHITE);
            
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_nombreDelObjetoTextFieldFocusGained

    private void nombreDelObjetoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreDelObjetoTextFieldFocusLost

        if (nombreDelObjetoTextField.getText().isEmpty()) {
            
            nombreDelObjetoTextField.setText("Gorra...");
            nombreDelObjetoTextField.setForeground(Color.GRAY);

            
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_nombreDelObjetoTextFieldFocusLost

    private void descripcionDelObjetoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descripcionDelObjetoTextFieldFocusGained

        if (descripcionDelObjetoTextField.getText().equals("Gorro de color rojo y blanco, con diseño,...")) {
            
            descripcionDelObjetoTextField.setText("");
            descripcionDelObjetoTextField.setForeground(Color.WHITE);

            
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_descripcionDelObjetoTextFieldFocusGained

    private void descripcionDelObjetoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descripcionDelObjetoTextFieldFocusLost

        if (descripcionDelObjetoTextField.getText().isEmpty()) {
            
            descripcionDelObjetoTextField.setText("Gorro de color rojo y blanco, con diseño,...");
            descripcionDelObjetoTextField.setForeground(Color.GRAY);

            
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_descripcionDelObjetoTextFieldFocusLost

    private void lugarYFechaTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lugarYFechaTextFieldFocusGained

        if (lugarYFechaTextField.getText().equals("Aula2 - Casa de la Cultura - 12/12/12")) {
            
            lugarYFechaTextField.setText("");
            lugarYFechaTextField.setForeground(Color.WHITE);

            
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_lugarYFechaTextFieldFocusGained

    private void lugarYFechaTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lugarYFechaTextFieldFocusLost

        if (lugarYFechaTextField.getText().isEmpty()) {
            
            lugarYFechaTextField.setText("Aula2 - Casa de la Cultura - 12/12/12");
            lugarYFechaTextField.setForeground(Color.GRAY);

            
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_lugarYFechaTextFieldFocusLost

    private void reportanteTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reportanteTextFieldFocusGained

        if (reportanteTextField.getText().equals("Nombres y apellidos")) {
            
            reportanteTextField.setText("");
            reportanteTextField.setForeground(Color.WHITE);

            
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_reportanteTextFieldFocusGained

    private void reportanteTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reportanteTextFieldFocusLost

        if (reportanteTextField.getText().isEmpty()) {
            
            reportanteTextField.setText("Nombres y apellidos");
            reportanteTextField.setForeground(Color.GRAY);

            
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_reportanteTextFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JComboBox<String> categoriaDelObjetoComboBox;
    private javax.swing.JTextField descripcionDelObjetoTextField;
    private javax.swing.JTextField lugarYFechaTextField;
    private javax.swing.JTextField nombreDelObjetoTextField;
    private javax.swing.JPanel registrarObjetoPerdidoPanel;
    private javax.swing.JPanel registrarObjetoPerdidoPanel1;
    private javax.swing.JPanel registrarObjetoPerdidoPanel2;
    private javax.swing.JPanel registrarObjetoPerdidoPanel3;
    private javax.swing.JPanel registrarObjetoPerdidoPanel4;
    private javax.swing.JPanel registrarObjetoPerdidoPanelTitulo;
    private javax.swing.JTextField reportanteTextField;
    // End of variables declaration//GEN-END:variables
}
