/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemadeobjetosperdidos;

/**
 *
 * @author ASUS
 */
public class registro extends javax.swing.JFrame {

    /**
     * Creates new form registro
     */
    public registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        registrarObjetoPerdidoPanelTitulo = new javax.swing.JPanel();
        registrarObjetoPerdidoLabel = new javax.swing.JLabel();
        registrarObjetoPerdidoPanel = new javax.swing.JPanel();
        nombreDelObjetoLabel = new javax.swing.JLabel();
        nombreDelObjetoTextField = new javax.swing.JTextField();
        descripcionDelObjetoLabel = new javax.swing.JLabel();
        descripcionDelObjetoTextField = new javax.swing.JTextField();
        categoriaDelObjetoLabel = new javax.swing.JLabel();
        categoriaDelObjetoComboBox = new javax.swing.JComboBox<>();
        lugarYFechaLabel = new javax.swing.JLabel();
        lugarYFechaTextField = new javax.swing.JTextField();
        reportanteLabel = new javax.swing.JLabel();
        reportanteTextField = new javax.swing.JTextField();
        registrarObjetoPerdidoPanelOpciones = new javax.swing.JPanel();
        aceptarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setBackground(new java.awt.Color(204, 204, 204));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrarObjetoPerdidoLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        registrarObjetoPerdidoLabel.setForeground(new java.awt.Color(255, 255, 255));
        registrarObjetoPerdidoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrarObjetoPerdidoLabel.setText("REGISTRO DE OBJETOS PERDIDOS");
        registrarObjetoPerdidoLabel.setToolTipText("");
        registrarObjetoPerdidoLabel.setAutoscrolls(true);

        javax.swing.GroupLayout registrarObjetoPerdidoPanelTituloLayout = new javax.swing.GroupLayout(registrarObjetoPerdidoPanelTitulo);
        registrarObjetoPerdidoPanelTitulo.setLayout(registrarObjetoPerdidoPanelTituloLayout);
        registrarObjetoPerdidoPanelTituloLayout.setHorizontalGroup(
            registrarObjetoPerdidoPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrarObjetoPerdidoPanelTituloLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(registrarObjetoPerdidoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        registrarObjetoPerdidoPanelTituloLayout.setVerticalGroup(
            registrarObjetoPerdidoPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarObjetoPerdidoPanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registrarObjetoPerdidoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        Menu.add(registrarObjetoPerdidoPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 120));

        registrarObjetoPerdidoPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nombreDelObjetoLabel.setText("NOMBRE DEL OBJETO:");

        nombreDelObjetoTextField.setForeground(new java.awt.Color(102, 102, 102));
        nombreDelObjetoTextField.setText("Ejm: Laptop, Pomo, Gorra, etc.");
        nombreDelObjetoTextField.setToolTipText("");
        nombreDelObjetoTextField.setCaretColor(new java.awt.Color(102, 102, 102));

        descripcionDelObjetoLabel.setText("DESCRIPCION DEL OBJETO:");

        descripcionDelObjetoTextField.setForeground(new java.awt.Color(102, 102, 102));
        descripcionDelObjetoTextField.setText("Ejm: Laptop, Pomo, Gorra, etc.");
        descripcionDelObjetoTextField.setToolTipText("");
        descripcionDelObjetoTextField.setCaretColor(new java.awt.Color(102, 102, 102));

        categoriaDelObjetoLabel.setText(" ELIJE UNA CATEGORIA PARA EL OBJETO:");

        categoriaDelObjetoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lugarYFechaLabel.setText("LUGAR Y FECHA DONDE SE ENCONTRO: ");

        lugarYFechaTextField.setForeground(new java.awt.Color(102, 102, 102));
        lugarYFechaTextField.setText("Ejm: Laptop, Pomo, Gorra, etc.");
        lugarYFechaTextField.setToolTipText("");
        lugarYFechaTextField.setCaretColor(new java.awt.Color(102, 102, 102));

        reportanteLabel.setText("NOMBRES Y APELLIDOS COMPLETOS DEL REPORTANTE:");

        reportanteTextField.setForeground(new java.awt.Color(102, 102, 102));
        reportanteTextField.setText("Ejm: Laptop, Pomo, Gorra, etc.");
        reportanteTextField.setToolTipText("");
        reportanteTextField.setCaretColor(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout registrarObjetoPerdidoPanelLayout = new javax.swing.GroupLayout(registrarObjetoPerdidoPanel);
        registrarObjetoPerdidoPanel.setLayout(registrarObjetoPerdidoPanelLayout);
        registrarObjetoPerdidoPanelLayout.setHorizontalGroup(
            registrarObjetoPerdidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarObjetoPerdidoPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(registrarObjetoPerdidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombreDelObjetoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoriaDelObjetoLabel)
                    .addComponent(descripcionDelObjetoLabel)
                    .addComponent(lugarYFechaLabel)
                    .addComponent(reportanteLabel)
                    .addComponent(nombreDelObjetoTextField)
                    .addComponent(descripcionDelObjetoTextField)
                    .addComponent(categoriaDelObjetoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lugarYFechaTextField)
                    .addComponent(reportanteTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        registrarObjetoPerdidoPanelLayout.setVerticalGroup(
            registrarObjetoPerdidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarObjetoPerdidoPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(nombreDelObjetoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreDelObjetoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(descripcionDelObjetoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descripcionDelObjetoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(categoriaDelObjetoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoriaDelObjetoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lugarYFechaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lugarYFechaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reportanteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reportanteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        Menu.add(registrarObjetoPerdidoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 380, 400));

        registrarObjetoPerdidoPanelOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registrarObjetoPerdidoPanelOpcionesLayout = new javax.swing.GroupLayout(registrarObjetoPerdidoPanelOpciones);
        registrarObjetoPerdidoPanelOpciones.setLayout(registrarObjetoPerdidoPanelOpcionesLayout);
        registrarObjetoPerdidoPanelOpcionesLayout.setHorizontalGroup(
            registrarObjetoPerdidoPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarObjetoPerdidoPanelOpcionesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(aceptarButton)
                .addGap(18, 18, 18)
                .addComponent(cancelarButton)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        registrarObjetoPerdidoPanelOpcionesLayout.setVerticalGroup(
            registrarObjetoPerdidoPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarObjetoPerdidoPanelOpcionesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(registrarObjetoPerdidoPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton)
                    .addComponent(aceptarButton))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Menu.add(registrarObjetoPerdidoPanelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 240, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JComboBox<String> categoriaDelObjetoComboBox;
    private javax.swing.JLabel categoriaDelObjetoLabel;
    private javax.swing.JLabel descripcionDelObjetoLabel;
    private javax.swing.JTextField descripcionDelObjetoTextField;
    private javax.swing.JLabel lugarYFechaLabel;
    private javax.swing.JTextField lugarYFechaTextField;
    private javax.swing.JLabel nombreDelObjetoLabel;
    private javax.swing.JTextField nombreDelObjetoTextField;
    private javax.swing.JLabel registrarObjetoPerdidoLabel;
    private javax.swing.JPanel registrarObjetoPerdidoPanel;
    private javax.swing.JPanel registrarObjetoPerdidoPanelOpciones;
    private javax.swing.JPanel registrarObjetoPerdidoPanelTitulo;
    private javax.swing.JLabel reportanteLabel;
    private javax.swing.JTextField reportanteTextField;
    // End of variables declaration//GEN-END:variables
}
